### ISSUE TITLE
Build Failure - missing dependencies 

### ISSUE THREAD

**Issue by madtomic** [darbyjack/Guilds-Plugin#102]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:06 min
[INFO] Finished at: 2019-03-01T08:52:20-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Guilds: Could not resolve dependencies for project me.glaremasters:Guilds:jar:3.4-BETA: Failed to collect dependencies at co.aikar:acf-bukkit:jar:0.5.0-SNAPSHOT: Failed to read artifact descriptor for co.aikar:acf-bukkit:jar:0.5.0-SNAPSHOT: Could not transfer artifact co.aikar:acf-bukkit:pom:0.5.0-SNAPSHOT from/to vault-repo (http://nexus.hc.to/content/repositories/pub_releases): Failed to transfer file: http://nexus.hc.to/content/repositories/pub_releases/co/aikar/acf-bukkit/0.5.0-SNAPSHOT/acf-bukkit-0.5.0-SNAPSHOT.pom. Return code is: 502 , ReasonPhrase:Bad Gateway. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by GMatrixGames** [comment]
Vault's Repo is down, he has to change it to the EnderZone jenkins repo

**Comment by darbyjack** [comment]
You need to be building from the develope branch.
