### ISSUE TITLE
Option to disable sections of the GUI display - i.e. disabling the members list to cut down on tooltip size.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#20]
Possible to disable parts of the GUI from showing? Lots of members kind of makes the tooltip a bit too large. 

![link](http://i.imgur.com/yxqIx4g.jpg)

I'd personally would probably only want to show the number of members on the GUI unless it was clicked on, for it to then output in chat a guild inspect of that guild.

**Comment by darbyjack** [comment]
Added the ability to change what shows here in latest commit.
