### ISSUE TITLE
JSON chat output on guild list GUI click.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#22]
With a split message of Join Guild | Inspect Guild to click in chat an option to either join the guild or inspect it for further chat output / info about the guild. So if you had some GUI hover info disabled, you could see the full guild details with member list in chat when clicking on that guild.

**Comment by darbyjack** [comment]
For now I won't be able to do this until I find something that will easily support Spigot / Bukkit. Feel free to re-open if you know of something that would work.
