### ISSUE TITLE
Guild inspect and guild accept <guild ID> are case sensitive.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#27]
If a town is named SuperTown, you can't join or inspect it via ```/guild inspect Supertown | /guild accept Supertown```. You must type it by its case specific name.

I also personally think /guild accept should automatically accept the invite if you only have 1 pending invite. Else list all pending invites for a guild a person could choose from to join. Perhaps a command to see pending invites too instead of only on login?

**Comment by darbyjack** [comment]
Fixed
