### ISSUE TITLE
Option to split guild info members in town list into multiple lore sections.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#29]
Would be better to split members by 5 per row or something in the lore of the item instead of one big long 
row display.

**Comment by darbyjack** [comment]
Added in latest update.

**Comment by mibby** [comment]
@darbyjack How about the cake in guild info? https://gyazo.com/e7be9af1cf4fc7eb60bf71d8115d1bbe

**Comment by darbyjack** [comment]
Found and fixed.
