### ISSUE TITLE
Be able to accept a guild invite without having to specify the name with '/guild accept' if it is the only pending invite available and implement a command to list all pending invites / turn down invite requests.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#30]
I personally think ```/guild accept``` should automatically accept a guild invite if you only have 1 pending invite. Otherwise require players to specify a guild to accept if you have multiple pending invites for guilds you can join. 

Perhaps also implement a command to see all active pending invites instead of only on login and a command to turn down a guild invite as well so it isn't permanently pending?

**Comment by darbyjack** [comment]
Implemented /guild check

**Comment by mibby** [comment]
What about accepting a pending invite if there is only 1 so you don't have to type the full guild name out?
