### ISSUE TITLE
Be able to accept a pending invite without having to specify the guild name if it is the only pending guild invite you have.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#34]
Guilds version 1.7.7-RELEASE

I personally think ```/guild accept``` should automatically accept a pending invite if you only have 1 invite from any guild pending. It is a bit silly to force require the guild name to be entered in ```/guild accept <name>``` with it being the only invite. Makes sense for a name to be entered if you have multiple invites from various guilds, not so much for just a single guild.

---

(Random Idea) Maybe in the future, be able to also list all pending invites via ```/guild check``` and output it as
1. Pending invite from Guild1Name
2. Pending invite from Guild2Name
3. Pending invite from Guild3Name
4. Pending invite from Guild4Name

So you can then ```/guild accept <pendingid>```?

**Comment by darbyjack** [comment]
The random idea is already implemented via /guild check and you would just do /guild join <GuildName>

**Comment by mibby** [comment]
@darbyjack So would that be a no then to being able to accept a guild invite with ```/guild accept``` without having to type the name of the guild if it is the only invite pending?
