### ISSUE TITLE
Guild master heads are not caching in the list GUI. It only displays the guild owner's head if they are online.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#37]
Guilds version 1.7.7-RELEASE

```/guild list``` does not show the heads of all guild owners. It only shows their correct head if they are online. If they are offline, it is either a default steve or default alex head.

Edit: Upon deleting my test guild I created, all the heads updated. So problem with it updating perhaps?

**Comment by darbyjack** [comment]
The caching of the heads goes via their playerdata and the Mojang API, simply closing the GUI and re-opening it will fix the issue.
