### ISSUE TITLE
Deleted guilds are not removing data information inside guild-status.yml

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#39]
Guilds version 1.7.7-RELEASE

Deleting a guild does not remove the information inputted in the guild-status.yml. I'm assuming guild-homes.yml doesn't remove deleted guild information either.

**Comment by darbyjack** [comment]
No it doesn't

**Comment by mibby** [comment]
Yes it does? I created a guild 'TestTown' and 'TestTown2' last night one after another, as well as deleted both of them consecutively. This information is still prevalent inside the status yml file. 

https://www.dropbox.com/s/rcpnsrutpat2kxy/data.zip?dl=0

**Comment by mibby** [comment]
This is also a problem with allied guilds. 

If Guild1 allies with Guild2, but then Guild2 deletes their guild, Guild1 is still allied with Guild2. Someone can then come along and create a new guild under the same name and be allied with Guild1 unintentionally.

**Comment by darbyjack** [comment]
Possibly fixed. Can let me know if it isn't.
