### ISSUE TITLE
Allow '/guild accept' without guild name if it is the only pending invite.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#44]
Third time's the charm? Asking again since there wasn't really a definitive answer in the other tickets.
https://github.com/darbyjack/Guilds-Plugin/issues/30
https://github.com/darbyjack/Guilds-Plugin/issues/34

```/guild accept``` should automatically accept a pending invite if you only have 1 invite from any guild pending. It is a bit silly to force the guild name to be entered in ```/guild accept <name>``` with it being the only invite. While it makes sense to specify a name when you have multiple invites, it is more tedious for the end user when they only have a single invite.

**Comment by darbyjack** [comment]
Done
