### ISSUE TITLE
Guild status in guild list - 'public' is lowercase whereas 'Private' is capitalized.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#50]
Guilds dev 73

Shouldn't 'public' be capitalized for consistency?

![link](http://i.imgur.com/TbBszH6.png)
![link2](http://i.imgur.com/S8Yy9ZN.png)

**Comment by darbyjack** [comment]
It shows however the user types it. If they do "public" it'll show "public", if they do "Public" it'll show "Public".

**Comment by mibby** [comment]
@darbyjack Is there any way to force it capitalized for consistency? Because if it is based on how the user types it, it could show up as pUbLiC.

**Comment by darbyjack** [comment]
Yes, I'll see if I can make it force capitalization.
