### ISSUE TITLE
Guild leader skulls do not update until after you open the guild list

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#51]
Guilds dev 73

* Opened the guild list for the first time since reboot via ```/guild list```
![link](http://i.imgur.com/f7GKpem.png)
* All guild leader skulls were default steve / alex except one person (who wasn't even online).
* Closed the GUI and typed ```/guild list``` again, the skulls updated.
![link2](http://i.imgur.com/Kh93KFw.png)

Would it be possible to force update the skulls with the corresponding UUID skin prior to the GUI being opened? Or keep a local guild-skulldata cache that refreshes when the command is ran? i.e.

* /guild list
* Skull data gets updated / loads recent update from cache
* GUI pops up

Rather than have to type the command twice to get heads to display properly.

**Comment by darbyjack** [comment]
I have looked into this before, and have also discussed with a few other developers, and it was said that it's best to leave it as is. It may be annoying, but it only happens once after a reboot. If it proceeds to get worse, I'll look into a better way (if there is one) to try and make this work.
