### ISSUE TITLE
Upon Updating Guilds - Guild database/names all disappear.

### ISSUE THREAD

**Issue by KnifeKat** [darbyjack/Guilds-Plugin#55]
Upon updating to the new Guilds, history/information/database(Whatever you're referencing it to): All the Guilds are wiped.

Old Plugin: Had Guild named SpigotGuild, upon updating it to the Guild Banks update, all Guilds in the server were wiped/deleted.

**Comment by darbyjack** [comment]
Haven't had any other reports of this issue, could not reproduce. Closing for the time being.
