### ISSUE TITLE
Should check ticket and avoid setting item air

### ISSUE THREAD

**Issue by prozhong** [darbyjack/Guilds-Plugin#61]
TicketListener.java#L42
When I have 64 upgrade tickets,  all of them will be deleted but my guild levels 1 up

And maybe should check more than ticket's display name, like material type,  lore

**Comment by darbyjack** [comment]
I can fix the all being deleted, but I don't see why you would have 64 upgrade tickets. The point of them is to be a rare chance of earning, so more than one would not profit you as a server owner because if you're charging heavy money for them, then it's harder to get. Anyways, I'll fix it.

**Comment by prozhong** [comment]
I was testing and used Essentials plugin's '/more' , so I got 64 tickets. lol

**Comment by darbyjack** [comment]
Ya, I kinda knew about this but was hoping it wouldn't be an issue. I'll investigate into more checks.

**Comment by darbyjack** [comment]
Should be fixed!
