### ISSUE TITLE
feature request - permission node for guild chat ChatColor usage

### ISSUE THREAD

**Issue by prozhong** [darbyjack/Guilds-Plugin#62]
I notice Guilds auto translate '&' to chat color
Maybe we need a permission node like guilds.command.chatcolor to control it

**Comment by darbyjack** [comment]
Have you tested this with a user who does and doesn't have essentials.chat.color?

**Comment by prozhong** [comment]
![20170910003656](https://user-images.githubusercontent.com/1495642/30241999-a33ab1ae-95c0-11e7-9615-10998e16bc7a.png)
I have a '-essentials.chat.color' node

**Comment by darbyjack** [comment]
Okay, I can look into adding a permission node for this.

If you want to just disable color codes in general, you can remove the & in the regex in the config.

**Comment by darbyjack** [comment]
Added when you toggle /guild chat
