### ISSUE TITLE
Guilds json file keeps resetting.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#66]
Guilds dev 174

The guilds json file keeps resetting and wiping all active guilds. This was first reported to me on September 14th so it must have broke somewhere between dev 151 and current dev 174. I tried manually removing the guilds json and having it re-create on the latest dev build, but it still seems to be resetting when people create and join guilds.

I have switched over to sql database support in the meantime to see if that functions without wiping.

**Comment by darbyjack** [comment]
Fixed
