### ISSUE TITLE
Ability to remove all hardcoded alias references to allow for renaming.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#9]
Guilds v1.6.1-RELEASE

I was also wondering if it was possible to remove all hardcoded references to the word 'guild'. I'm trying to rename things to town instead as I don't want people to mistake Guilds for factions, but it seems to be hardcoded all over the place. Even the prefix didn't change when reloading the config.

![link](http://i.imgur.com/hnI20EW.png)

English.yml
http://paste.ubuntu.com/25018448/

Config.yml
http://paste.ubuntu.com/25018450/

Plugin.yml
http://paste.ubuntu.com/25018454/

**Comment by darbyjack** [comment]
Fixed with latest update
